package domain

var Categories = []Category{
	{Slug: "crm", Name: "CRM", Description: "Pipelines, contacts, the usual sales chaos."},
	{Slug: "sales", Name: "Sales", Description: "Outreach, quotes, and closing the deal."},
	{Slug: "analytics", Name: "Analytics", Description: "Dashboards people actually open."},
	{Slug: "billing", Name: "Billing", Description: "Subscriptions, invoices, getting paid."},
	{Slug: "payments", Name: "Payments", Description: "Checkout, cards, and money moving."},
	{Slug: "ai", Name: "AI", Description: "Copilots, wrappers, agents."},
	{Slug: "agents", Name: "Agents", Description: "Bots that do the work, or try to."},
	{Slug: "chatbots", Name: "Chatbots", Description: "The ones in the corner of every site."},
	{Slug: "marketing", Name: "Marketing", Description: "The tools that fill the funnel."},
	{Slug: "ads", Name: "Ads", Description: "Spend money, hope it comes back."},
	{Slug: "seo", Name: "SEO", Description: "Rankings, keywords, the long game."},
	{Slug: "content", Name: "Content", Description: "Write it, ship it, recycle it."},
	{Slug: "email", Name: "Email", Description: "Campaigns, sequences, the inbox war."},
	{Slug: "newsletters", Name: "Newsletters", Description: "Substack energy, but as a product."},
	{Slug: "social", Name: "Social", Description: "Scheduling posts and chasing reach."},
	{Slug: "affiliates", Name: "Affiliates", Description: "Pay people to talk about you."},
	{Slug: "productivity", Name: "Productivity", Description: "Notes, tasks, the app you'll use this time."},
	{Slug: "project-management", Name: "Project management", Description: "Boards, timelines, status theater."},
	{Slug: "docs", Name: "Docs", Description: "Wikis that might stay up to date."},
	{Slug: "notes", Name: "Notes", Description: "Capture it before it disappears."},
	{Slug: "spreadsheets", Name: "Spreadsheets", Description: "Still running half the company."},
	{Slug: "presentations", Name: "Presentations", Description: "Slides that don't look like 2014."},
	{Slug: "whiteboard", Name: "Whiteboard", Description: "Infinite canvas, finite attention."},
	{Slug: "developer-tools", Name: "Developer tools", Description: "CI, deploys, the stack behind the stack."},
	{Slug: "devops", Name: "DevOps", Description: "Pipelines, infra, please don't page me."},
	{Slug: "observability", Name: "Observability", Description: "Logs, traces, and the 3am graph."},
	{Slug: "testing", Name: "Testing", Description: "QA, e2e, the stuff that should've caught it."},
	{Slug: "feature-flags", Name: "Feature flags", Description: "Ship dark, flip later."},
	{Slug: "apis", Name: "APIs", Description: "Endpoints, keys, rate limits."},
	{Slug: "databases", Name: "Databases", Description: "Store it, query it, don't lose it."},
	{Slug: "hosting", Name: "Hosting", Description: "Where the site actually lives."},
	{Slug: "cms", Name: "CMS", Description: "Edit the page without calling engineering."},
	{Slug: "no-code", Name: "No-code", Description: "Build it without a repo."},
	{Slug: "low-code", Name: "Low-code", Description: "A little code, a lot of glue."},
	{Slug: "automation", Name: "Automation", Description: "If this, then that. All day."},
	{Slug: "internal-tools", Name: "Internal tools", Description: "The admin panel nobody markets."},
	{Slug: "support", Name: "Support", Description: "Inboxes and help desks."},
	{Slug: "customer-success", Name: "Customer success", Description: "Keep them around after the sale."},
	{Slug: "onboarding", Name: "Onboarding", Description: "First-run, checklists, don't lose them."},
	{Slug: "knowledge-base", Name: "Knowledge base", Description: "Help articles people might read."},
	{Slug: "community", Name: "Community", Description: "Forums, groups, the hangout."},
	{Slug: "communication", Name: "Communication", Description: "Chat, calls, too many channels."},
	{Slug: "meetings", Name: "Meetings", Description: "Notes, recordings, this could've been an email."},
	{Slug: "scheduling", Name: "Scheduling", Description: "Find a time. Finally."},
	{Slug: "calendar", Name: "Calendar", Description: "Who's free and who isn't."},
	{Slug: "video", Name: "Video", Description: "Record, edit, hop on a call."},
	{Slug: "design", Name: "Design", Description: "Figma cousins and brand kits."},
	{Slug: "photo", Name: "Photo", Description: "Edit, store, look sharper."},
	{Slug: "writing", Name: "Writing", Description: "Drafts, grammar, the blinking cursor."},
	{Slug: "translation", Name: "Translation", Description: "Ship in more than one language."},
	{Slug: "hr", Name: "HR", Description: "People ops, time off, the handbook."},
	{Slug: "recruiting", Name: "Recruiting", Description: "Jobs, pipelines, the interview loop."},
	{Slug: "finance", Name: "Finance", Description: "Books, forecasts, the board deck."},
	{Slug: "accounting", Name: "Accounting", Description: "Ledgers, close, don't miss a receipt."},
	{Slug: "invoicing", Name: "Invoicing", Description: "Send the bill, chase the bill."},
	{Slug: "tax", Name: "Tax", Description: "The annual nightmare, slightly less bad."},
	{Slug: "legal", Name: "Legal", Description: "Contracts, e-sign, the fine print."},
	{Slug: "compliance", Name: "Compliance", Description: "SOC 2, GDPR, the audit folder."},
	{Slug: "security", Name: "Security", Description: "Locks, scans, sleep a bit better."},
	{Slug: "identity", Name: "Identity", Description: "Login, SSO, who are you."},
	{Slug: "passwords", Name: "Passwords", Description: "Vaults and the one you reused."},
	{Slug: "privacy", Name: "Privacy", Description: "Consent, cookies, do not sell."},
	{Slug: "storage", Name: "Storage", Description: "Files, backups, the shared drive."},
	{Slug: "search", Name: "Search", Description: "Find it without scrolling forever."},
	{Slug: "forms", Name: "Forms", Description: "Typeform energy. Collect the answers."},
	{Slug: "surveys", Name: "Surveys", Description: "Ask, wait, screenshot the NPS."},
	{Slug: "feedback", Name: "Feedback", Description: "What users actually think."},
	{Slug: "ab-testing", Name: "A/B testing", Description: "Ship two versions, pick a winner."},
	{Slug: "personalization", Name: "Personalization", Description: "Different page for different people."},
	{Slug: "ecommerce", Name: "Ecommerce", Description: "Stores, carts, the thank-you page."},
	{Slug: "marketplaces", Name: "Marketplaces", Description: "Buyers, sellers, take a cut."},
	{Slug: "education", Name: "Education", Description: "Courses, cohorts, the LMS."},
	{Slug: "healthcare", Name: "Healthcare", Description: "Clinics, patients, the HIPAA pile."},
	{Slug: "real-estate", Name: "Real estate", Description: "Listings, tours, the open house."},
	{Slug: "travel", Name: "Travel", Description: "Trips, tickets, the itinerary."},
	{Slug: "logistics", Name: "Logistics", Description: "Ship it, track it, don't lose it."},
	{Slug: "manufacturing", Name: "Manufacturing", Description: "The floor, the inventory, the delay."},
	{Slug: "construction", Name: "Construction", Description: "Jobsites, bids, weather delays."},
	{Slug: "food", Name: "Food", Description: "Menus, delivery, reservations."},
	{Slug: "fitness", Name: "Fitness", Description: "Workouts, coaches, the streak."},
	{Slug: "gaming", Name: "Gaming", Description: "Studios, servers, the launch day."},
	{Slug: "music", Name: "Music", Description: "Make it, sell it, tour it."},
	{Slug: "fashion", Name: "Fashion", Description: "Drops, fits, the lookbook."},
	{Slug: "beauty", Name: "Beauty", Description: "Skincare, bookings, the glow-up."},
	{Slug: "sports", Name: "Sports", Description: "Teams, tickets, the recap."},
	{Slug: "news", Name: "News", Description: "Publish, paywall, the morning brief."},
	{Slug: "events", Name: "Events", Description: "Tickets, badges, the afterparty."},
	{Slug: "webinars", Name: "Webinars", Description: "Register, mute, follow-up."},
	{Slug: "podcasts", Name: "Podcasts", Description: "Record, host, the 4-star review."},
	{Slug: "crypto", Name: "Crypto", Description: "Wallets, on-chain, the chart."},
	{Slug: "web3", Name: "Web3", Description: "Same as crypto, different slide."},
	{Slug: "climate", Name: "Climate", Description: "Carbon, energy, the hard problem."},
	{Slug: "nonprofit", Name: "Nonprofit", Description: "Donations, volunteers, the mission."},
	{Slug: "government", Name: "Government", Description: "Civic tools, slow procurement."},
	{Slug: "insurance", Name: "Insurance", Description: "Quotes, claims, the deductible."},
	{Slug: "banking", Name: "Banking", Description: "Accounts, ledgers, the charter."},
	{Slug: "iot", Name: "IoT", Description: "Devices, firmware, the blinking light."},
	{Slug: "mobile", Name: "Mobile", Description: "Apps, stores, the push notification."},
	{Slug: "browser-extensions", Name: "Browser extensions", Description: "A little power in the toolbar."},
	{Slug: "maps", Name: "Maps", Description: "Pins, routes, don't get lost."},
	{Slug: "voice", Name: "Voice", Description: "Calls, IVR, talk to the robot."},
	{Slug: "sms", Name: "SMS", Description: "Texts that aren't spam. Ideally."},
	{Slug: "push", Name: "Push", Description: "The ping you meant to send."},
	{Slug: "file-sharing", Name: "File sharing", Description: "Send the thing without emailing a zip."},
	{Slug: "backup", Name: "Backup", Description: "Hope you never need it."},
	{Slug: "vpn", Name: "VPN", Description: "A tunnel and a new IP."},
	{Slug: "monitoring", Name: "Monitoring", Description: "Uptime, alerts, the red bar."},
	{Slug: "status-pages", Name: "Status pages", Description: "We're investigating. We always are."},
	{Slug: "okrs", Name: "OKRs", Description: "Goals you revisit in Q4."},
	{Slug: "time-tracking", Name: "Time tracking", Description: "Where the week actually went."},
	{Slug: "kids", Name: "Kids", Description: "For parents, schools, the tiny users."},
	{Slug: "pets", Name: "Pets", Description: "Vets, sitters, the goodest products."},
}

var categoryIndex = func() map[string]Category {
	out := make(map[string]Category, len(Categories))
	for _, category := range Categories {
		out[category.Slug] = category
	}
	return out
}()

func KnownCategory(slug string) bool {
	_, ok := categoryIndex[slug]
	return ok
}

func GetCategory(slug string) (Category, bool) {
	category, ok := categoryIndex[slug]
	return category, ok
}
